"""add_fire_reports_table

Revision ID: 4472ffe70e8d
Revises: 9215fedfe454
Create Date: 2025-12-30 21:43:55.188556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4472ffe70e8d'
down_revision: Union[str, Sequence[str], None] = '9215fedfe454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fire_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fire_reports_id'), 'fire_reports', ['id'], unique=False)
    op.create_unique_constraint(None, 'fire_incidents', ['id'])
    op.create_unique_constraint(None, 'fire_stations', ['id'])
    op.create_unique_constraint(None, 'smoke_detections', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'smoke_detections', type_='unique')
    op.drop_constraint(None, 'fire_stations', type_='unique')
    op.drop_constraint(None, 'fire_incidents', type_='unique')
    op.drop_index(op.f('ix_fire_reports_id'), table_name='fire_reports')
    op.drop_table('fire_reports')
    # ### end Alembic commands ###
